Repository vergecurrency/vIOS, pull requests merged in 2019-02, with the labels that each got.

#117 #104 fix
  VergeiOS/Kernel/Wallet/WalletClient.swift
Labels: bug

#125 fix 118-119
  VergeiOS.xcodeproj/project.pbxproj
  VergeiOS/Components/Notification/NotificationManager.swift
  VergeiOS/Controllers/Settings/AddressesTableViewController.swift
  VergeiOS/Extensions/UIView+Actions.swift
Labels: bug

#127 Verify received address #101
  VergeiOS/Wallet/WalletClient.swift
Labels: BWS, enhancement

#128 Restrict the maximum of fraction digits 🧩
  VergeiOS/Components/UI/Inputs/CurrencyInput.swift
  VergeiOS/Extensions/NSNumber+Currency.swift
  VergeiOS/Utils/Constants.swift
Labels: bug

#133 Add transaction proposals management 🏋️‍♀️
  VergeiOS.xcodeproj/project.pbxproj
  VergeiOS/Assets.xcassets/Icons/Quill.imageset/Contents.json
  VergeiOS/Assets.xcassets/Icons/Quill.imageset/icons8-quill-with-ink.pdf
  VergeiOS/Assets/Settings.storyboard
  VergeiOS/Controllers/Send/SendViewController.swift
  VergeiOS/Controllers/Settings/AddressesTableViewController.swift
  VergeiOS/Controllers/Settings/TransactionProposalsTableViewController.swift
  VergeiOS/Wallet/WalletClient.swift
Labels: enhancement
